### ISSUE TITLE
Inquiry about purchasing a domain you own

### ISSUE THREAD

**Issue by VisEntities** [mattivaisanen/wenwipe#1]
Hi there,

I tried to send you an email, but it seems like your email server is down. I hope it's alright if I reach out to you here. I am interested in buying the domain you are currently holding (wenwipe.com) for personal use. Please let me know if you are open to selling it and what your asking price would be.

Thank you,
Dana

**Comment by mattivaisanen** [comment]
Hi!
I could be interested! How much were you thinking?

-Matti

ti 9. toukok. 2023 klo 19.45 Dana ***@***.***) kirjoitti:

**Comment by VisEntities** [comment]
Thanks for your quick response. I was thinking around $50 for the domain. If that works for you, we can continue the conversation on Discord (Dana#5247) and discuss the details.
